[package]
authors = ["The Rust Project Developers"]
name = "libtest"
version = "0.0.0"
edition = "2018"

[lib]
name = "libtest"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
getopts = "0.2"
term = { path = "../libterm" }